#############################################################################
# Makefile for building: Codici
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  Codici.pro
# Template: app
# Command: /usr/lib64/qt5/bin/qmake -o Makefile Codici.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib64/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Codici1.0.0
DISTDIR = /home/penaz/Documenti/Universita'/Informatica/Passati/Programmazione_2/Progetto/Codici/.tmp/Codici1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lGLESv2 -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		DataStructs/MultimediaItem.cpp \
		DataStructs/Software.cpp \
		DataStructs/Video.cpp \
		GUI/addItem.cpp \
		GUI/addUser.cpp \
		GUI/itemSearchWidget.cpp \
		GUI/loggedUserWidget.cpp \
		GUI/loginWidget.cpp \
		GUI/mainWidget.cpp \
		GUI/mainWindow.cpp \
		GUI/registrationForm.cpp \
		GUI/sidebarWidget.cpp \
		GUI/userSearchWidget.cpp \
		GUI/viewEditItem.cpp \
		GUI/viewEditUser.cpp \
		UserStructs/Admin.cpp \
		UserStructs/Developer.cpp \
		UserStructs/Editor.cpp \
		UserStructs/User.cpp \
		Utilities/UserUtilities.cpp \
		Utilities/XMLUtilities.cpp moc_addItem.cpp \
		moc_addUser.cpp \
		moc_itemSearchWidget.cpp \
		moc_loggedUserWidget.cpp \
		moc_loginWidget.cpp \
		moc_mainWidget.cpp \
		moc_mainWindow.cpp \
		moc_registrationForm.cpp \
		moc_sidebarWidget.cpp \
		moc_userSearchWidget.cpp \
		moc_viewEditItem.cpp \
		moc_viewEditUser.cpp
OBJECTS       = main.o \
		MultimediaItem.o \
		Software.o \
		Video.o \
		addItem.o \
		addUser.o \
		itemSearchWidget.o \
		loggedUserWidget.o \
		loginWidget.o \
		mainWidget.o \
		mainWindow.o \
		registrationForm.o \
		sidebarWidget.o \
		userSearchWidget.o \
		viewEditItem.o \
		viewEditUser.o \
		Admin.o \
		Developer.o \
		Editor.o \
		User.o \
		UserUtilities.o \
		XMLUtilities.o \
		moc_addItem.o \
		moc_addUser.o \
		moc_itemSearchWidget.o \
		moc_loggedUserWidget.o \
		moc_loginWidget.o \
		moc_mainWidget.o \
		moc_mainWindow.o \
		moc_registrationForm.o \
		moc_sidebarWidget.o \
		moc_userSearchWidget.o \
		moc_viewEditItem.o \
		moc_viewEditUser.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		Codici.pro DataStructs/MultimediaItem.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		GUI/addItem.h \
		GUI/addUser.h \
		GUI/itemSearchWidget.h \
		GUI/loggedUserWidget.h \
		GUI/loginWidget.h \
		GUI/mainWidget.h \
		GUI/mainWindow.h \
		GUI/registrationForm.h \
		GUI/sidebarWidget.h \
		GUI/userSearchWidget.h \
		GUI/viewEditItem.h \
		GUI/viewEditUser.h \
		UserStructs/Admin.h \
		UserStructs/Developer.h \
		UserStructs/Editor.h \
		UserStructs/User.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		DataStructs/Unused/VideoGame.h main.cpp \
		DataStructs/MultimediaItem.cpp \
		DataStructs/Software.cpp \
		DataStructs/Video.cpp \
		GUI/addItem.cpp \
		GUI/addUser.cpp \
		GUI/itemSearchWidget.cpp \
		GUI/loggedUserWidget.cpp \
		GUI/loginWidget.cpp \
		GUI/mainWidget.cpp \
		GUI/mainWindow.cpp \
		GUI/registrationForm.cpp \
		GUI/sidebarWidget.cpp \
		GUI/userSearchWidget.cpp \
		GUI/viewEditItem.cpp \
		GUI/viewEditUser.cpp \
		UserStructs/Admin.cpp \
		UserStructs/Developer.cpp \
		UserStructs/Editor.cpp \
		UserStructs/User.cpp \
		Utilities/UserUtilities.cpp \
		Utilities/XMLUtilities.cpp
QMAKE_TARGET  = Codici
DESTDIR       = 
TARGET        = Codici


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Codici.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		Codici.pro \
		/usr/lib64/libQt5Widgets.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile Codici.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
Codici.pro:
/usr/lib64/libQt5Widgets.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Codici.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents DataStructs/MultimediaItem.h DataStructs/Software.h DataStructs/Video.h GUI/addItem.h GUI/addUser.h GUI/itemSearchWidget.h GUI/loggedUserWidget.h GUI/loginWidget.h GUI/mainWidget.h GUI/mainWindow.h GUI/registrationForm.h GUI/sidebarWidget.h GUI/userSearchWidget.h GUI/viewEditItem.h GUI/viewEditUser.h UserStructs/Admin.h UserStructs/Developer.h UserStructs/Editor.h UserStructs/User.h Utilities/UserUtilities.h Utilities/XMLUtilities.h DataStructs/Unused/VideoGame.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp DataStructs/MultimediaItem.cpp DataStructs/Software.cpp DataStructs/Video.cpp GUI/addItem.cpp GUI/addUser.cpp GUI/itemSearchWidget.cpp GUI/loggedUserWidget.cpp GUI/loginWidget.cpp GUI/mainWidget.cpp GUI/mainWindow.cpp GUI/registrationForm.cpp GUI/sidebarWidget.cpp GUI/userSearchWidget.cpp GUI/viewEditItem.cpp GUI/viewEditUser.cpp UserStructs/Admin.cpp UserStructs/Developer.cpp UserStructs/Editor.cpp UserStructs/User.cpp Utilities/UserUtilities.cpp Utilities/XMLUtilities.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_addItem.cpp moc_addUser.cpp moc_itemSearchWidget.cpp moc_loggedUserWidget.cpp moc_loginWidget.cpp moc_mainWidget.cpp moc_mainWindow.cpp moc_registrationForm.cpp moc_sidebarWidget.cpp moc_userSearchWidget.cpp moc_viewEditItem.cpp moc_viewEditUser.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_addItem.cpp moc_addUser.cpp moc_itemSearchWidget.cpp moc_loggedUserWidget.cpp moc_loginWidget.cpp moc_mainWidget.cpp moc_mainWindow.cpp moc_registrationForm.cpp moc_sidebarWidget.cpp moc_userSearchWidget.cpp moc_viewEditItem.cpp moc_viewEditUser.cpp
moc_addItem.cpp: DataStructs/MultimediaItem.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		UserStructs/User.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		UserStructs/Developer.h \
		GUI/addItem.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed -I/usr/include GUI/addItem.h -o moc_addItem.cpp

moc_addUser.cpp: UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		UserStructs/Developer.h \
		UserStructs/Editor.h \
		DataStructs/Software.h \
		UserStructs/Admin.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		DataStructs/Video.h \
		GUI/addUser.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed -I/usr/include GUI/addUser.h -o moc_addUser.cpp

moc_itemSearchWidget.cpp: UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		UserStructs/Editor.h \
		GUI/itemSearchWidget.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed -I/usr/include GUI/itemSearchWidget.h -o moc_itemSearchWidget.cpp

moc_loggedUserWidget.cpp: UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		GUI/loggedUserWidget.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed -I/usr/include GUI/loggedUserWidget.h -o moc_loggedUserWidget.cpp

moc_loginWidget.cpp: UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		Utilities/UserUtilities.h \
		GUI/loginWidget.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed -I/usr/include GUI/loginWidget.h -o moc_loginWidget.cpp

moc_mainWidget.cpp: GUI/loggedUserWidget.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		GUI/sidebarWidget.h \
		GUI/addItem.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		UserStructs/Developer.h \
		GUI/itemSearchWidget.h \
		GUI/userSearchWidget.h \
		GUI/viewEditItem.h \
		GUI/viewEditUser.h \
		GUI/addUser.h \
		GUI/mainWidget.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed -I/usr/include GUI/mainWidget.h -o moc_mainWidget.cpp

moc_mainWindow.cpp: GUI/loginWidget.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		Utilities/UserUtilities.h \
		GUI/registrationForm.h \
		Utilities/XMLUtilities.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		UserStructs/Developer.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		GUI/mainWidget.h \
		GUI/loggedUserWidget.h \
		GUI/sidebarWidget.h \
		GUI/addItem.h \
		GUI/itemSearchWidget.h \
		GUI/userSearchWidget.h \
		GUI/viewEditItem.h \
		GUI/viewEditUser.h \
		GUI/addUser.h \
		GUI/mainWindow.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed -I/usr/include GUI/mainWindow.h -o moc_mainWindow.cpp

moc_registrationForm.cpp: UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		UserStructs/Developer.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		GUI/registrationForm.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed -I/usr/include GUI/registrationForm.h -o moc_registrationForm.cpp

moc_sidebarWidget.cpp: GUI/addItem.h \
		DataStructs/MultimediaItem.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		UserStructs/User.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		UserStructs/Developer.h \
		GUI/sidebarWidget.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed -I/usr/include GUI/sidebarWidget.h -o moc_sidebarWidget.cpp

moc_userSearchWidget.cpp: UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		GUI/userSearchWidget.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed -I/usr/include GUI/userSearchWidget.h -o moc_userSearchWidget.cpp

moc_viewEditItem.cpp: DataStructs/MultimediaItem.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		UserStructs/User.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		UserStructs/Developer.h \
		GUI/viewEditItem.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed -I/usr/include GUI/viewEditItem.h -o moc_viewEditItem.cpp

moc_viewEditUser.cpp: UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		UserStructs/Developer.h \
		UserStructs/Editor.h \
		DataStructs/Software.h \
		UserStructs/Admin.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		DataStructs/Video.h \
		GUI/viewEditUser.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I'/home/penaz/Documenti/Universita'\''/Informatica/Passati/Programmazione_2/Progetto/Codici' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5 -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include-fixed -I/usr/include GUI/viewEditUser.h -o moc_viewEditUser.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp GUI/mainWindow.h \
		GUI/loginWidget.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		Utilities/UserUtilities.h \
		GUI/registrationForm.h \
		Utilities/XMLUtilities.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		UserStructs/Developer.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		GUI/mainWidget.h \
		GUI/loggedUserWidget.h \
		GUI/sidebarWidget.h \
		GUI/addItem.h \
		GUI/itemSearchWidget.h \
		GUI/userSearchWidget.h \
		GUI/viewEditItem.h \
		GUI/viewEditUser.h \
		GUI/addUser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MultimediaItem.o: DataStructs/MultimediaItem.cpp DataStructs/MultimediaItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MultimediaItem.o DataStructs/MultimediaItem.cpp

Software.o: DataStructs/Software.cpp DataStructs/Software.h \
		DataStructs/MultimediaItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Software.o DataStructs/Software.cpp

Video.o: DataStructs/Video.cpp DataStructs/Video.h \
		DataStructs/MultimediaItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Video.o DataStructs/Video.cpp

addItem.o: GUI/addItem.cpp GUI/addItem.h \
		DataStructs/MultimediaItem.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		UserStructs/User.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		UserStructs/Developer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addItem.o GUI/addItem.cpp

addUser.o: GUI/addUser.cpp GUI/addUser.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		UserStructs/Developer.h \
		UserStructs/Editor.h \
		DataStructs/Software.h \
		UserStructs/Admin.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		DataStructs/Video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addUser.o GUI/addUser.cpp

itemSearchWidget.o: GUI/itemSearchWidget.cpp GUI/itemSearchWidget.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		UserStructs/Editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o itemSearchWidget.o GUI/itemSearchWidget.cpp

loggedUserWidget.o: GUI/loggedUserWidget.cpp GUI/loggedUserWidget.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loggedUserWidget.o GUI/loggedUserWidget.cpp

loginWidget.o: GUI/loginWidget.cpp GUI/loginWidget.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		Utilities/UserUtilities.h \
		GUI/registrationForm.h \
		Utilities/XMLUtilities.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		UserStructs/Developer.h \
		DataStructs/Software.h \
		DataStructs/Video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginWidget.o GUI/loginWidget.cpp

mainWidget.o: GUI/mainWidget.cpp GUI/mainWidget.h \
		GUI/loggedUserWidget.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		GUI/sidebarWidget.h \
		GUI/addItem.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		UserStructs/Developer.h \
		GUI/itemSearchWidget.h \
		GUI/userSearchWidget.h \
		GUI/viewEditItem.h \
		GUI/viewEditUser.h \
		GUI/addUser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWidget.o GUI/mainWidget.cpp

mainWindow.o: GUI/mainWindow.cpp GUI/mainWindow.h \
		GUI/loginWidget.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		Utilities/UserUtilities.h \
		GUI/registrationForm.h \
		Utilities/XMLUtilities.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		UserStructs/Developer.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		GUI/mainWidget.h \
		GUI/loggedUserWidget.h \
		GUI/sidebarWidget.h \
		GUI/addItem.h \
		GUI/itemSearchWidget.h \
		GUI/userSearchWidget.h \
		GUI/viewEditItem.h \
		GUI/viewEditUser.h \
		GUI/addUser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindow.o GUI/mainWindow.cpp

registrationForm.o: GUI/registrationForm.cpp GUI/registrationForm.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		UserStructs/Developer.h \
		DataStructs/Software.h \
		DataStructs/Video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registrationForm.o GUI/registrationForm.cpp

sidebarWidget.o: GUI/sidebarWidget.cpp GUI/sidebarWidget.h \
		GUI/addItem.h \
		DataStructs/MultimediaItem.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		UserStructs/User.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		UserStructs/Developer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sidebarWidget.o GUI/sidebarWidget.cpp

userSearchWidget.o: GUI/userSearchWidget.cpp GUI/userSearchWidget.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userSearchWidget.o GUI/userSearchWidget.cpp

viewEditItem.o: GUI/viewEditItem.cpp GUI/viewEditItem.h \
		DataStructs/MultimediaItem.h \
		DataStructs/Software.h \
		DataStructs/Video.h \
		UserStructs/User.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		UserStructs/Developer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewEditItem.o GUI/viewEditItem.cpp

viewEditUser.o: GUI/viewEditUser.cpp GUI/viewEditUser.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		UserStructs/Developer.h \
		UserStructs/Editor.h \
		DataStructs/Software.h \
		UserStructs/Admin.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		DataStructs/Video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewEditUser.o GUI/viewEditUser.cpp

Admin.o: UserStructs/Admin.cpp UserStructs/Admin.h \
		UserStructs/Editor.h \
		DataStructs/MultimediaItem.h \
		UserStructs/User.h \
		Utilities/UserUtilities.h \
		Utilities/XMLUtilities.h \
		UserStructs/Developer.h \
		DataStructs/Software.h \
		DataStructs/Video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Admin.o UserStructs/Admin.cpp

Developer.o: UserStructs/Developer.cpp UserStructs/Developer.h \
		UserStructs/Editor.h \
		DataStructs/MultimediaItem.h \
		UserStructs/User.h \
		DataStructs/Software.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Developer.o UserStructs/Developer.cpp

Editor.o: UserStructs/Editor.cpp UserStructs/Editor.h \
		DataStructs/MultimediaItem.h \
		UserStructs/User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Editor.o UserStructs/Editor.cpp

User.o: UserStructs/User.cpp UserStructs/User.h \
		DataStructs/MultimediaItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o UserStructs/User.cpp

UserUtilities.o: Utilities/UserUtilities.cpp Utilities/UserUtilities.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UserUtilities.o Utilities/UserUtilities.cpp

XMLUtilities.o: Utilities/XMLUtilities.cpp Utilities/XMLUtilities.h \
		UserStructs/User.h \
		DataStructs/MultimediaItem.h \
		UserStructs/Admin.h \
		UserStructs/Editor.h \
		Utilities/UserUtilities.h \
		UserStructs/Developer.h \
		DataStructs/Software.h \
		DataStructs/Video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XMLUtilities.o Utilities/XMLUtilities.cpp

moc_addItem.o: moc_addItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addItem.o moc_addItem.cpp

moc_addUser.o: moc_addUser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addUser.o moc_addUser.cpp

moc_itemSearchWidget.o: moc_itemSearchWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_itemSearchWidget.o moc_itemSearchWidget.cpp

moc_loggedUserWidget.o: moc_loggedUserWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loggedUserWidget.o moc_loggedUserWidget.cpp

moc_loginWidget.o: moc_loginWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginWidget.o moc_loginWidget.cpp

moc_mainWidget.o: moc_mainWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWidget.o moc_mainWidget.cpp

moc_mainWindow.o: moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWindow.o moc_mainWindow.cpp

moc_registrationForm.o: moc_registrationForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registrationForm.o moc_registrationForm.cpp

moc_sidebarWidget.o: moc_sidebarWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sidebarWidget.o moc_sidebarWidget.cpp

moc_userSearchWidget.o: moc_userSearchWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userSearchWidget.o moc_userSearchWidget.cpp

moc_viewEditItem.o: moc_viewEditItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewEditItem.o moc_viewEditItem.cpp

moc_viewEditUser.o: moc_viewEditUser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewEditUser.o moc_viewEditUser.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

